### ISSUE TITLE
Round Profile Image 기능 

### ISSUE THREAD

**Issue by thekan23** [synature14/Diary#3]
- 직사각형 모양의 ImageView를 원형으로 만든다

예시코드) 
```swift
        let imageView = UIImageView(frame: CGRect(x: 0, y: 0, width: 70, height: 70))
        imageView.image = UIImage(named: "sutie")
        imageView.cornerRadius = imageView.frame.width / 2
        imageView.clipsToBounds = true
 ```

**Comment by synature14** [comment]
url에서 가져온 데이터를 UIImage 오브젝트에 넣어  
        let picData = try! Data(contentsOf: url!)
        let image = UIImage(data: picData)!
image.af_imageAspectScaled(toFit: size)
image.af_imageRounded(withCornerRadius: radius)
image.af_imageRoundedIntoCircle()

위와 같은 UIImage의 메소드를 사용하여 해결하였습니다.
