### ISSUE TITLE
DetailPage 기능

### ISSUE THREAD

**Issue by thekan23** [synature14/Diary#5]
ProfileList에서 특정 profile를 tap 하면 자세한 정보가 나타나는 Detail Page로 이동하게 만들어 주세요
디자인은 아무렇게나 해도 상관없지만 tap된 profile와 같은 정보를 보여주어야 합니다.

Navigation Controller / Present Modally 아무거나 사용해도 무방합니다.

**Comment by synature14** [comment]
unwind segue로 구현해보았습니다 :)

**Comment by synature14** [comment]
dismiss로 구현해 보았습니다.
detailPage에 프로필 배경사진도 추가했습니다.
